import clusterReport from './cluster-report.json';
import testResults from './test-results.json';
import impactMap from './impact-map.json';

export const fallbackAdapterCode = `/**
 * Migration Adapter Shim (Generated by APIShift Module B)
 * Provides backward-compatibility between legacy callers (before.yaml)
 * and updated API services (after.yaml).
 */

export interface LegacyGetOrderResponse {
  id: string;
  totalAmount?: number;
  total?: number;
  status: string;
  [key: string]: any;
}

export interface LegacyCreateOrderPayload {
  customer_id?: string;
  customer?: { id: string };
  items: Array<{ itemId: string; quantity: number }>;
  coupon_code?: string;
  [key: string]: any;
}

export class MigrationAdapter {
  private enabled: boolean = false;

  constructor(enabled: boolean = false) {
    this.enabled = enabled;
  }

  public setAdapterEnabled(enabled: boolean) {
    this.enabled = enabled;
  }

  public isAdapterEnabled(): boolean {
    return this.enabled;
  }

  /**
   * Adapts incoming GET /api/orders/{id} response.
   * If totalAmount is present and total is missing, populates total.
   */
  public adaptGetOrderResponse<T extends LegacyGetOrderResponse>(response: T): T {
    if (!this.enabled) return response;
    if (response && response.totalAmount !== undefined && response.total === undefined) {
      return {
        ...response,
        total: response.totalAmount,
      };
    }
    return response;
  }

  /**
   * Adapts outgoing POST /api/orders request payload.
   * If customer_id is present and customer object is missing, maps customer: { id: customer_id }.
   */
  public adaptCreateOrderPayload<T extends LegacyCreateOrderPayload>(payload: T): T {
    if (!this.enabled) return payload;
    if (payload && payload.customer_id && !payload.customer) {
      const { customer_id, ...rest } = payload;
      return {
        ...rest,
        customer_id,
        customer: { id: customer_id },
      } as T;
    }
    return payload;
  }
}

export const migrationAdapter = new MigrationAdapter(true);
`;

export const fallbackArtifacts = {
  clusterReport,
  testResults,
  impactMap,
  adapterCode: fallbackAdapterCode,
  bobSessions: {
    totalBobcoins: 1.09,
    sessionCount: 4,
    sessions: [
      { name: "team_task01_impact_analysis_summary.png", path: "/bob_sessions/team_task01_impact_analysis_summary.png", status: "LOGGED" },
      { name: "team_task02_migration_codegen_summary.png", path: "/bob_sessions/team_task02_migration_codegen_summary.png", status: "LOGGED" },
      { name: "team_task03_failure_clustering_summary.png", path: "/bob_sessions/team_task03_failure_clustering_summary.png", status: "LOGGED" },
      { name: "team_task04_rootcause_fix_summary.png", path: "/bob_sessions/team_task04_rootcause_fix_summary.png", status: "LOGGED" }
    ]
  }
};

export const fallbackClusterReport = clusterReport;
export const fallbackImpactMap = impactMap;
export const fallbackTestResults = testResults;
export const fallbackBobSessions = fallbackArtifacts.bobSessions;
